### ISSUE TITLE
add option to log 95% (or other percentiles) of timer value to individual metrics

### ISSUE THREAD

**Issue by frkline** [blacklocus/metrics-cloudwatch#6]
while this wouldn't be a 1:1 mapping to the existing metrics, currently only logging average and max makes it difficult to understand the real-world experience.

**Comment by dirkraft** [comment]
The reporter's job is simply to log the atomic data. If the data is basic and pristine, then any kind reporting on it is possible whether simple sums and averages, or percentiles, histograms whatever. The CloudWatch **UI** only does sums, averages, min, max; that is its reporting limitation. All the data is there in its pure form and you could pull it out of there to calculate these values; the CloudWatch UI just doesn't offer rolling up these metrics for you. The CloudWatch Java API doesn't even offer aggregations (no sums, no averages), it only offers giving you back your datapoints, because that is what the CloudWatch API actually is. They just happened to build a few basic aggregation functions into the console.

Overloading the raw datapoints with more meaning (assumptions) such as submitting calculated averages or percentiles or anything you can imagine, you would then be locked into a very specific meaning of what each reported datapoint (MetricDatum or StatisticSet) stood for. Then aggregation over these datapoints would be extremely particular. Those scenarios are not generalizable for all users of CloudWatch, so submitting overloaded (any computed or derived values) isn't supported.

I considered mapping such *derived* metrics as they are made available by coda hale's metrics constructs. But after coming back out of that rabbit hole I decided that such derived metrics are really the responsibility of the reporting application (in our case the AWS stock CloudWatch UI). If CloudWatch had a way to store these precomputed values and then sensibly aggregate over them, I would have ported them. But CloudWatch is based only on MetricDatum (simple scalar datapoints) and StatisticSets (something to represent a more continuous space of value rather than discrete scalars).
